# we excplicitly use tag with runner hostname to ensure stages on the same runner
# this brakes parallelism but makes things much clearer and simplier

stages:
- make_deb_v1

make_deb_v1:
  tags:
    - dev1.sysadm.ws
  stage: make_deb_v1
  artifacts:
    name: v1
    paths:
      - builds/v1
  only:
    refs:
      - master
  script: |
    mkdir -p builds/v1/DEBIAN
    export NEW_VERSION=$(curl -s https://repo.sysadm.ws/sysadmws-apt/dists/any/main/binary-amd64/Packages | grep -Pzo 'Package: sysadmws-utils-v1\n.*\n.*\n.*\n.*\n' | grep --text 'Version' | sed -e 's/Version: 1\.//')
    cat deb/control | sed -e "s#__NEW_VERSION__#$NEW_VERSION#" > builds/v1/DEBIAN/control
